const firebase = require("firebase"); //gerenciador do firebase
const configFirebase = require("./firebase");//conexão com o realtime database

//configuracao do firebase
//as informações do banco do firebase devem ser adicionadas no arquivo firebase.js no diretorio firebase/database
var config = {
    apiKey: configFirebase.apiKey,
    authDomain: configFirebase.authDomain,
    databaseURL:  configFirebase.databaseURL,
    storageBucket: configFirebase.storageBucket
};

//armazenamento dos serviços
var servicosSalvos = [];

firebase.initializeApp(config);

// Pega uma referência para o database firebase do campo de serviços
var servicos = firebase.database().ref("servicos");
servicos.on('value',function(data){
    servicosSalvos = data;
});

// funções responsaveis por gerir a parte de serviços TCP
function salvarTCP(nome, ip, porta){
    // Generate a reference to a new location and add some data using push()
    var servicosRef = servicos.push();
    // Get the unique key generated by push()
    var servicosId = servicosRef.key;     
    //salva a informação no banco de dados no firebase
    servicosRef.set({
        nome,
        ip,
        porta,
        diretorio: '',
        id: servicosId
    });
}

function editarTCP(nome,ip,porta,id){
    firebase.database().ref("servicos/" + id).set({
        nome,
        ip,
        porta,
        diretorio: '',
        id
    });
}

//funções para gerir a parte de serviços Arquivos

function salvarArquivo(nome, dir){
    // Generate a reference to a new location and add some data using push()
    var servicosRef = servicos.push();
    // Get the unique key generated by push()
    var servicosId = servicosRef.key;     
    //salva a informação no banco de dados no firebase
    servicosRef.set({
        nome: nome,
        ip: '',
        porta: '',
        diretorio: dir,
        id: servicosId
    });
}

function editarArquivo(nome, dir,id){
    //salva no firebase
    firebase.database().ref("servicos/" + id).set({
        nome: nome,
        ip: '',
        porta: '',
        diretorio: dir,
        id: id
    });
}

//funções para gerir os serviços
function deletarService(id){
    firebase.database().ref("servicos/" + id).remove();
}

function getServices(){
    return servicosSalvos;
}


module.exports = {salvarTCP,getServices,editarTCP,deletarService,salvarArquivo,editarArquivo}